const translations = {
  en: {
    nav: { home: "Home", projects: "Projects", dashboard: "Dashboard", profile: "Profile", calendar: "Calendar", admin: "Admin", login: "Login", register: "Register", logout: "Logout" },
    home: { hero_eyebrow: "Casting Agency · Slovakia", hero_title: "YOUR ROLE AWAITS", hero_title_line2: "Your talent\non screen", hero_subtitle: "We connect acting and non-acting performers with film and television productions. Join thousands of registered extras.", cta_browse: "Browse Projects", cta_register: "Join as Actor", cta_register_long: "Register Now", cta_our_projects: "Our Projects", scroll_hint: "Scroll", stats_projects: "Active Projects", stats_actors: "Registered Extras", stats_productions: "Films & Series", stats_years: "Years of Experience", projects_title: "OPEN CASTINGS", projects_subtitle: "Find your next role", view_all: "View All Projects", all_projects: "All Projects", apply_now: "Apply Now", spots_left: "spots left", full: "FULL", no_open_castings: "No open castings at the moment.",
      about_eyebrow: "About cineCAST", about_title_pre: "Connecting ", about_title_highlight: "talent", about_title_post: " with story", about_body: "Cinecast is a young casting agency founded in 2025 by people with years of experience in the film industry. We operate on both the Slovak and international markets, providing casting for films, series, and advertising projects. We collaborate with major producers and directors from Slovakia and the Czech Republic, unafraid of challenges or unconventional solutions. Our ambition is to connect talents with opportunities and build a professional environment where casting is more than just selection – it is a creative process. We believe that precise casting can determine the success of a project. Therefore, we emphasize detail, speed, and open communication.", about_feature_1_title: "Professional Approach", about_feature_1_desc: "Years of experience in film and advertising allow us to provide top-tier service.", about_feature_2_title: "Extensive Database", about_feature_2_desc: "Our database includes thousands of people of all age categories and types.", about_feature_3_title: "Free Registration", about_feature_3_desc: "Registration with us is always free. No fees, ever.", about_years_label: "Years Experience",
      portfolio_eyebrow: "Our Portfolio", portfolio_title: "PROJECTS WE ARE PROUD OF", portfolio_done: "Done", portfolio_more: "More coming soon", portfolio_archive: "Archive Project", portfolio_year: "Year", portfolio_director: "Director", portfolio_based_on: "Based on", portfolio_screenplay: "Screenplay", portfolio_cinematography: "Cinematography", portfolio_cast: "Cast", portfolio_synopsis: "Synopsis",
      how_eyebrow: "How it works", how_title: "Get Started", how_step: "Step", how_step1_title: "Online Registration", how_step1_body: "Fill out the registration form with basic details and measurements.", how_step2_title: "Add Photos", how_step2_body: "Natural photos of your face and body are enough. No pro shots needed.", how_step3_title: "Browse Projects", how_step3_body: "Browse open castings and apply for positions that match your profile.", how_step4_title: "Earnings & Experience", how_step4_body: "Enjoy the atmosphere on set and get paid for your work.", how_cta_title: "Registration is Free!", how_cta_body: "Join thousands of people who discovered the world of film production.", how_cta_button: "Register for Free",
      testimonials_eyebrow: "What Our Performers Say", testimonials_title: "Success Stories", testimonial_1_quote: "Filming the movie Štúr, where I portrayed a scribe at the Hungarian Diet, was an unforgettable experience. Thanks to Cinecast, everything went smoothly — from communication to on-set organisation. I appreciated the professional yet friendly atmosphere and the opportunity to be part of a major historical film. I can only recommend Cinecast to anyone who wants to try working in film or TV.", testimonial_1_role: "Extra with years of experience", testimonial_2_quote: "Professional and fair approach. Communication was fast, everything went without a hitch and I felt very comfortable. I can definitely recommend this agency to everyone.", testimonial_2_role: "Extra with years of experience", testimonial_3_quote: "From registration to shooting, everything was perfectly organized. CineCAST truly cares about its talents.", testimonial_3_role: "Commercial Talent", testimonial_4_quote: "I registered on a whim and within two weeks I was on set for a national TV campaign. The team kept me updated every step of the way.", testimonial_4_role: "Commercial Talent", testimonial_5_quote: "As a student looking for extra income, CineCAST gave me steady opportunities on film sets without any hidden fees. It's been a great experience.", testimonial_5_role: "Extra, Feature Film", testimonial_6_quote: "What stood out was how quickly they matched my profile to a role. Clear communication, fair pay, and a real production on a real set.", testimonial_6_role: "Background Actor, Series",
      partners_eyebrow: "Our Partners", partners_title: "WE WORK WITH THE BEST",
      contact_eyebrow: "Have Questions?", contact_title: "Get in Touch", contact_body: "Have questions about registration, current projects, or need assistance? We're here for you.", contact_form_title: "Send Message", contact_name: "Name", contact_name_placeholder: "Your name", contact_message: "Message", contact_message_placeholder: "Your message...", contact_send: "Send Message" },
    projects: { title: "PROJECTS", subtitle: "Browse all open castings", search_placeholder: "Search projects...", filter_all: "All Types", filter_movie: "Movie", filter_tv: "TV Series", filter_commercial: "Commercial", filter_documentary: "Documentary", filter_music_video: "Music Video", filter_other: "Other", no_results: "No projects found.", positions: "positions" },
    project_detail: { back: "Back to Projects", apply: "Apply for this Position", waitlist: "Join Waitlist", full: "Position Full", spots: "spots available", director: "Director", company: "Production Company", location: "Location", shooting: "Shooting Dates", positions_title: "Open Positions", age: "Age", gender: "Gender", skills: "Required Skills", languages: "Required Languages", compensation: "Compensation", date: "Shooting Date", time: "Time" },
    apply: { title: "Apply for Position", name: "Full Name", email: "Email", phone: "Phone", message: "Message / Cover Letter", submit: "Submit Application", submitting: "Submitting...", success: "Application submitted successfully!", guest_note: "Applying as guest. Register for full features.", login_prompt: "Already have an account?", login_link: "Log in" },
    dashboard: { title: "MY DASHBOARD", subtitle: "Your casting overview", upcoming: "Upcoming Shoots", applied: "My Applications", notifications: "Notifications", no_upcoming: "No upcoming shoots scheduled.", no_upcoming_hint: "Accepted applications with a shooting date will show up here.", no_applied: "You haven't applied to any projects yet.", no_applied_hint: "Find a role that fits and send your first application.", no_notifications: "You're all caught up!", no_notifications_hint: "We'll let you know when something changes.", status_pending: "Pending", status_accepted: "Accepted", status_rejected: "Rejected", status_waitlist: "Waitlist", status_cancelled: "Cancelled", browse_projects: "Browse Projects", confirmed: "Confirmed", greeting: "Hey, {name}", stat_applications: "Applications", stat_pending: "Pending", stat_accepted: "Accepted", stat_unread: "Unread", group_applications: "Your Applications", group_notifications: "Notifications", unknown_project: "Unknown Project", unknown_position: "Unknown Position", admin_note: "Note from the team", applied_on: "Applied", position_label: "Position" },
    profile: { title: "MY PROFILE", save: "Save Changes", saving: "Saving...", saved: "Saved!", tab_personal: "Personal", tab_appearance: "Appearance", tab_skills: "Skills & Languages", tab_experience: "Experience", tab_details: "Details", tab_gallery: "Gallery", tab_security: "Security", first_name: "First Name", last_name: "Last Name", email: "Email", phone: "Phone", bio: "Bio", city: "City", country: "Country", birthdate: "Birth Date", gender: "Gender", height: "Height (cm)", weight: "Weight (kg)", hair_color: "Hair Color", eye_color: "Eye Color", clothing_size: "Clothing Size", shoe_size: "Shoe Size", skills: "Skills", languages: "Languages", experience: "Experience / CV", add_skill: "Add skill", add_language: "Add language", upload_photo: "Upload Photo", gallery_hint: "Upload and reorder your photos" },
    calendar: { title: "MY CALENDAR", subtitle: "Your shooting schedule", no_events: "No shoots scheduled." },
    admin: { title: "ADMIN PANEL", subtitle: "Platform management", tab_projects: "Projects", tab_applications: "Applications", tab_users: "Users", tab_audit: "Audit Log", new_project: "New Project", edit: "Edit", delete: "Delete", archive: "Archive", publish: "Publish", duplicate: "Duplicate", accept: "Accept", reject: "Reject", waitlist: "Waitlist", stats_total: "Total Applications", stats_pending: "Pending", stats_accepted: "Accepted", stats_rejected: "Rejected", back_to_users: "Back to users", add_user: "Add User", gender_any: "Any", gender_male: "Male", gender_female: "Female", no_photos: "No photos uploaded yet.", user_applications_title: "User Applications", no_user_applications: "No applications from this user.", user_not_found: "User not found.", full_name: "Full Name", email: "Email", phone: "Phone", city: "City", country: "Country", birthdate: "Birth Date", gender: "Gender", bio: "Bio", height: "Height", weight: "Weight", hair_color: "Hair Color", eye_color: "Eye Color", clothing_size: "Clothing Size", shoe_size: "Shoe Size", skills: "Skills", languages: "Languages", years_old: "years old", member_since: "Member since", not_available: "N/A", unknown_project: "Unknown Project", unknown_position: "Unknown Position" },
    common: { loading: "Loading...", error: "An error occurred.", close: "Close", save: "Save", cancel: "Cancel", confirm: "Confirm", search: "Search", open: "Open", closed: "Closed", full: "Full", draft: "Draft", archived: "Archived", movie: "Movie", tv_series: "TV Series", commercial: "Commercial", documentary: "Documentary", music_video: "Music Video", other: "Other", any: "Any", male: "Male", female: "Female" },
    layout: { about_us: "About Us", contact: "Contact", admin_projects: "Admin Projects", applications: "Applications", users: "Users", audit_logs: "Audit Logs", register_now: "Register Now", footer_description: "Slovak casting agency based in Bratislava. We specialize in finding extras and actors for film and television productions.", footer_company: "Company", footer_navigation: "Navigation", footer_legal_support: "Legal & Support", privacy_policy: "Privacy Policy", terms_of_service: "Terms of Service", cookie_policy: "Cookie Policy", support: "Support", footer_rights: "All rights reserved.", theme_light_mode: "Light Mode", theme_dark_mode: "Dark Mode" },
    project_form: {
      create_title: "Create Project", edit_title: "Edit Project", update_button: "Update Project", publish_button: "Publish Project",
      back_to_projects: "Back to Projects",
      section_general: "General Information", section_production: "Production", section_cover: "Cover Image", section_gallery: "Project Gallery", section_roles: "Roles & Positions",
      project_name: "Project Name", project_name_placeholder: "e.g. Operation Fortune", project_type: "Project Type", status: "Status",
      live_schedule_title: "Live Casting Schedule", live_schedule_hint: "Pick the date range, the daily interview window, and the slot length. Bookable time slots are generated automatically for each day in the range.",
      start_date: "Start Date", end_date: "End Date", daily_start_time: "Daily Start Time", daily_end_time: "Daily End Time", slot_length: "Slot Length (Mins)", total_bookable_slots: "Total Bookable Slots:",
      short_description: "Short Description", short_description_placeholder: "A brief summary for project cards...", full_description: "Full Description", full_description_placeholder: "Detailed breakdown...",
      director: "Director", company: "Company", location: "Location",
      change_cover: "Change Cover", upload_cover: "Upload Cover", upload_cover_hint: "Drag & drop or click to upload",
      upload_gallery_image: "Upload Gallery Image", upload_gallery_hint: "Drag & drop or click to add images", no_gallery_images: "No gallery images uploaded yet.",
      add_role: "Add Role", role_title: "Role Title", role_title_placeholder: "e.g. Background Extra", spots: "Spots", date: "Date", gender: "Gender", age_min: "Age Min", age_max: "Age Max",
      field_required: "This field is required.", end_after_start: "End date must be after start date.", end_time_after_start: "End time must be after start time.",
    },
  },
  sk: {
    nav: { home: "Domov", projects: "Projekty", dashboard: "Dashboard", profile: "Profil", calendar: "Kalendár", admin: "Admin", login: "Prihlásenie", register: "Registrácia", logout: "Odhlásiť" },
    home: { hero_eyebrow: "Castingová agentúra · Slovensko", hero_title: "TVOJA ROLA ŤA ČAKÁ", hero_title_line2: "Váš talent\nna plátne", hero_subtitle: "Spájame hereckých a nehereckých účinkujúcich s filmovými a televíznymi produkciami. Pridajte sa k tisíckam registrovaných figurantov.", cta_browse: "Prehliadať projekty", cta_register: "Registrovať sa", cta_register_long: "Chcem sa registrovať", cta_our_projects: "Naše projekty", scroll_hint: "Scrollovať", stats_projects: "Aktívne projekty", stats_actors: "Registrovaní figuranti", stats_productions: "Filmov a seriálov", stats_years: "Rokov skúseností", projects_title: "OTVORENÉ CASTINGY", projects_subtitle: "Nájdi svoju ďalšiu rolu", view_all: "Všetky projekty", all_projects: "Všetky projekty", apply_now: "Prihlásiť sa", spots_left: "voľných miest", full: "OBSADENÉ", no_open_castings: "Žiadne otvorené castingy.",
      about_eyebrow: "O cineCAST", about_title_pre: "Spájame ", about_title_highlight: "talent", about_title_post: " s príbehom", about_body: "Cinecast je mladá castingová agentúra založená v roku 2025 ľuďmi s dlhoročnými skúsenosťami vo filmovom priemysle. Pôsobíme na slovenskom aj medzinárodnom trhu a zabezpečujeme casting pre filmy, seriály a reklamné projekty. Spolupracujeme s poprednými producentmi a režisérmi zo Slovenska a Českej republiky, pričom sa nebojíme výziev ani nekonvenčných riešení. Našou ambíciou je spájať talenty s príležitosťami a budovať profesionálne prostredie, kde casting nie je len výberom – je to tvorivý proces. Veríme, že presný casting môže rozhodnúť o úspechu projektu. Preto kladieme dôraz na detail, rýchlosť a otvorenú komunikáciu.", about_feature_1_title: "Profesionálny prístup", about_feature_1_desc: "Dlhoročné skúsenosti v oblasti filmu a reklamy nám umožňujú poskytovať špičkový servis.", about_feature_2_title: "Rozsiahla databáza", about_feature_2_desc: "Naša databáza zahŕňa tisíce ľudí všetkých vekových kategórií a typov.", about_feature_3_title: "Bezplatná registrácia", about_feature_3_desc: "Registrácia u nás je vždy bezplatná. Žiadne poplatky.", about_years_label: "Rokov skúseností",
      portfolio_eyebrow: "Naša vizitka", portfolio_title: "PROJEKTY, NA KTORÉ SME HRDÍ", portfolio_done: "Dokončené", portfolio_more: "Viac v príprave", portfolio_archive: "Archívny Projekt", portfolio_year: "Rok", portfolio_director: "Réžia", portfolio_based_on: "Predloha", portfolio_screenplay: "Scenár", portfolio_cinematography: "Kamera", portfolio_cast: "Hrajú", portfolio_synopsis: "Synopsa",
      how_eyebrow: "Postup", how_title: "Ako začať?", how_step: "Krok", how_step1_title: "Online registrácia", how_step1_body: "Vyplňte registračný formulár so základnými údajmi a mierami.", how_step2_title: "Pridajte fotografie", how_step2_body: "Stačia prirodzené fotky tváre a postavy. Nemusia byť od profesionála.", how_step3_title: "Sledujte projekty", how_step3_body: "Prehliadajte otvorené castingy a prihláste sa na pozície, ktoré vám sedia.", how_step4_title: "Zárobok a zážitok", how_step4_body: "Užite si atmosféru na pľaci a získajte honorár za vašu prácu.", how_cta_title: "Registrácia je bezplatná!", how_cta_body: "Pridajte sa k tisíckam ľudí, ktorí objavili svet filmovej produkcie.", how_cta_button: "Registrovať sa zadarmo",
      testimonials_eyebrow: "Čo hovoria naši účinkujúci", testimonials_title: "Úspešné príbehy", testimonial_1_quote: "Natáčanie filmu Štúr, kde som stvárnil pisára na uhorskom sneme, bolo pre mňa nezabudnuteľným zážitkom. Vďaka agentúre Cinecast prebehlo všetko hladko, od komunikácie až po organizáciu na mieste. Páčila sa mi profesionálna, ale zároveň priateľská atmosféra a možnosť byť súčasťou veľkého historického filmu. Cinecast môžem len odporučiť každému, kto si chce vyskúšať prácu vo filme či seriáli.", testimonial_1_role: "komparzista s dlhoročnými skúsenosťami", testimonial_2_quote: "Profesionálny a férový prístup. Komunikácia bola rýchla, všetko prebehlo bez problémov a cítil som sa veľmi príjemne. Agentúru môžem určite odporučiť každému.", testimonial_2_role: "komparzista s dlhoročnými skúsenosťami", testimonial_3_quote: "Od registrácie po natáčanie bolo všetko perfektne zorganizované. CineCAST sa skutočne stará o svoje talenty.", testimonial_3_role: "Tvár reklamy", testimonial_4_quote: "Registrovala som sa len tak a do dvoch týždňov som bola na pľaci celonárodnej televíznej reklamy. Tím ma informoval o každom kroku.", testimonial_4_role: "Tvár reklamy", testimonial_5_quote: "Ako študentka hľadajúca privyrobenie mi CineCAST dával pravidelné príležitosti na filmových pľacoch bez skrytých poplatkov. Bola to skvelá skúsenosť.", testimonial_5_role: "Komparz, celovečerný film", testimonial_6_quote: "Zaujalo ma, ako rýchlo dokázali nájsť rolu presne na mieru môjmu profilu. Jasná komunikácia, férová odmena a skutočná produkcia na ozajstnom pľaci.", testimonial_6_role: "Štatista, seriál",
      partners_eyebrow: "Naši partneri", partners_title: "SPOLUPRACUJEME S NAJLEPŠÍMI",
      contact_eyebrow: "Máte otázky?", contact_title: "Napíšte nám", contact_body: "Máte otázky ohľadom registrácie, aktuálnych projektov alebo potrebujete pomoc? Sme tu pre vás.", contact_form_title: "Správa", contact_name: "Meno", contact_name_placeholder: "Vaše meno", contact_message: "Správa", contact_message_placeholder: "Vaša správa...", contact_send: "Odoslať správu" },
    projects: { title: "PROJEKTY", subtitle: "Prehliadajte všetky otvorené castingy", search_placeholder: "Hľadať projekty...", filter_all: "Všetky typy", filter_movie: "Film", filter_tv: "TV Seriál", filter_commercial: "Reklama", filter_documentary: "Dokumentárny", filter_music_video: "Videoklip", filter_other: "Iné", no_results: "Žiadne projekty nenájdené.", positions: "pozícií" },
    project_detail: { back: "Späť na projekty", apply: "Prihlásiť sa na pozíciu", waitlist: "Čakacia listina", full: "Pozícia obsadená", spots: "voľných miest", director: "Režisér", company: "Produkčná spoločnosť", location: "Miesto", shooting: "Dátumy nakrúcania", positions_title: "Otvorené pozície", age: "Vek", gender: "Pohlavie", skills: "Požadované zručnosti", languages: "Požadované jazyky", compensation: "Odmena", date: "Dátum nakrúcania", time: "Čas" },
    apply: { title: "Prihláška na pozíciu", name: "Celé meno", email: "Email", phone: "Telefón", message: "Správa / Motivačný list", submit: "Odoslať prihlášku", submitting: "Odosiela sa...", success: "Prihláška bola úspešne odoslaná!", guest_note: "Prihlasujete sa ako hosť. Zaregistrujte sa pre plné funkcie.", login_prompt: "Máte účet?", login_link: "Prihláste sa" },
    dashboard: { title: "MÔJ DASHBOARD", subtitle: "Prehľad vašich castingov", upcoming: "Nadchádzajúce natáčania", applied: "Moje prihlášky", notifications: "Notifikácie", no_upcoming: "Žiadne naplánované natáčania.", no_upcoming_hint: "Prijaté prihlášky s termínom natáčania sa zobrazia tu.", no_applied: "Zatiaľ ste sa neprihlásili na žiadny projekt.", no_applied_hint: "Nájdite si rolu, ktorá vám sadne, a odošlite prvú prihlášku.", no_notifications: "Ste v obraze!", no_notifications_hint: "Ozveme sa, hneď ako sa niečo zmení.", status_pending: "Čaká", status_accepted: "Prijatý", status_rejected: "Odmietnutý", status_waitlist: "Čakacia listina", status_cancelled: "Zrušený", browse_projects: "Prehliadať projekty", confirmed: "Potvrdené", greeting: "Ahoj, {name}", stat_applications: "Prihlášky", stat_pending: "Čakajúce", stat_accepted: "Prijaté", stat_unread: "Neprečítané", group_applications: "Vaše prihlášky", group_notifications: "Notifikácie", unknown_project: "Neznámy projekt", unknown_position: "Neznáma pozícia", admin_note: "Poznámka od tímu", applied_on: "Prihlásené", position_label: "Pozícia" },
    profile: { title: "MÔJ PROFIL", save: "Uložiť zmeny", saving: "Ukladá sa...", saved: "Uložené!", tab_personal: "Osobné", tab_appearance: "Vzhľad", tab_skills: "Zručnosti a jazyky", tab_experience: "Skúsenosti", tab_details: "Detaily", tab_gallery: "Galéria", tab_security: "Bezpečnosť", first_name: "Meno", last_name: "Priezvisko", email: "Email", phone: "Telefón", bio: "Bio", city: "Mesto", country: "Krajina", birthdate: "Dátum narodenia", gender: "Pohlavie", height: "Výška (cm)", weight: "Hmotnosť (kg)", hair_color: "Farba vlasov", eye_color: "Farba očí", clothing_size: "Veľkosť oblečenia", shoe_size: "Veľkosť topánok", skills: "Zručnosti", languages: "Jazyky", experience: "Skúsenosti / CV", add_skill: "Pridať zručnosť", add_language: "Pridať jazyk", upload_photo: "Nahrať fotku", gallery_hint: "Nahrajte a usporiadajte svoje fotografie" },
    calendar: { title: "MÔJ KALENDÁR", subtitle: "Váš plán natáčania", no_events: "Žiadne naplánované natáčania." },
    admin: { title: "ADMIN PANEL", subtitle: "Správa platformy", tab_projects: "Projekty", tab_applications: "Prihlášky", tab_users: "Používatelia", tab_audit: "Audit log", new_project: "Nový projekt", edit: "Upraviť", delete: "Vymazať", archive: "Archivovať", publish: "Publikovať", duplicate: "Duplikovať", accept: "Prijať", reject: "Odmietnuť", waitlist: "Čakacia listina", stats_total: "Celkom prihlášok", stats_pending: "Čakajúce", stats_accepted: "Prijaté", stats_rejected: "Odmietnuté", back_to_users: "Späť na používateľov", add_user: "Pridať používateľa", gender_any: "Akékoľvek", gender_male: "Muž", gender_female: "Žena", no_photos: "Žiadne fotografie nenahrané.", user_applications_title: "Prihlášky používateľa", no_user_applications: "Tento používateľ sa zatiaľ neprihlásil na žiadny projekt.", user_not_found: "Používateľ nebol nájdený.", full_name: "Celé meno", email: "Email", phone: "Telefón", city: "Mesto", country: "Krajina", birthdate: "Dátum narodenia", gender: "Pohlavie", bio: "Bio", height: "Výška", weight: "Hmotnosť", hair_color: "Farba vlasov", eye_color: "Farba očí", clothing_size: "Veľkosť oblečenia", shoe_size: "Veľkosť topánok", skills: "Zručnosti", languages: "Jazyky", years_old: "rokov", member_since: "Registrovaný od", not_available: "N/A", unknown_project: "Neznámy projekt", unknown_position: "Neznáma pozícia" },
    common: { loading: "Načítava sa...", error: "Nastala chyba.", close: "Zavrieť", save: "Uložiť", cancel: "Zrušiť", confirm: "Potvrdiť", search: "Hľadať", open: "Otvorený", closed: "Uzavretý", full: "Obsadené", draft: "Koncept", archived: "Archivovaný", movie: "Film", tv_series: "TV Seriál", commercial: "Reklama", documentary: "Dokumentárny", music_video: "Videoklip", other: "Iné", any: "Akékoľvek", male: "Muž", female: "Žena" },
    layout: { about_us: "O nás", contact: "Kontakt", admin_projects: "Projekty (Admin)", applications: "Prihlášky", users: "Používatelia", audit_logs: "Audit Logs", register_now: "Registrovať sa", footer_description: "Slovenská castingová agentúra so sídlom v Bratislave. Špecializujeme sa na vyhľadávanie komparzu a hercov pre filmové a televízne produkcie.", footer_company: "Spoločnosť", footer_navigation: "Navigácia", footer_legal_support: "Právne a podpora", privacy_policy: "Ochrana osobných údajov", terms_of_service: "Podmienky používania", cookie_policy: "Zásady cookies", support: "Podpora", footer_rights: "Všetky práva vyhradené.", theme_light_mode: "Svetlý režim", theme_dark_mode: "Tmavý režim" },
    project_form: {
      create_title: "Vytvoriť projekt", edit_title: "Upraviť projekt", update_button: "Aktualizovať projekt", publish_button: "Publikovať projekt",
      back_to_projects: "Späť na projekty",
      section_general: "Základné informácie", section_production: "Produkcia", section_cover: "Titulný obrázok", section_gallery: "Galéria projektu", section_roles: "Role a pozície",
      project_name: "Názov projektu", project_name_placeholder: "napr. Operation Fortune", project_type: "Typ projektu", status: "Stav",
      live_schedule_title: "Harmonogram live castingu", live_schedule_hint: "Vyberte rozsah dátumov, denné okno na pohovory a dĺžku jedného slotu. Voľné termíny sa pre každý deň v rozsahu vygenerujú automaticky.",
      start_date: "Dátum začiatku", end_date: "Dátum konca", daily_start_time: "Denný začiatok", daily_end_time: "Denný koniec", slot_length: "Dĺžka slotu (min)", total_bookable_slots: "Celkový počet termínov:",
      short_description: "Krátky popis", short_description_placeholder: "Stručné zhrnutie pre kartu projektu...", full_description: "Celý popis", full_description_placeholder: "Podrobný popis projektu...",
      director: "Režisér", company: "Spoločnosť", location: "Miesto",
      change_cover: "Zmeniť titulný obrázok", upload_cover: "Nahrať titulný obrázok", upload_cover_hint: "Presuňte sem súbor alebo kliknite pre nahratie",
      upload_gallery_image: "Nahrať fotku do galérie", upload_gallery_hint: "Presuňte sem súbory alebo kliknite pre nahratie", no_gallery_images: "Zatiaľ neboli nahrané žiadne fotky do galérie.",
      add_role: "Pridať rolu", role_title: "Názov role", role_title_placeholder: "napr. Komparz", spots: "Počet miest", date: "Dátum", gender: "Pohlavie", age_min: "Min. vek", age_max: "Max. vek",
      field_required: "Toto pole je povinné.", end_after_start: "Dátum konca musí byť po dátume začiatku.", end_time_after_start: "Čas konca musí byť po čase začiatku.",
    },
  },
};

export function getLang() {
  return localStorage.getItem("cinecast_lang") || "sk";
}

export function setLang(lang) {
  localStorage.setItem("cinecast_lang", lang);
  window.dispatchEvent(new Event("langchange"));
}

export function t(section, key) {
  const lang = getLang();
  return translations[lang]?.[section]?.[key] ?? translations["en"]?.[section]?.[key] ?? key;
}